/*
 * This file is generated by jOOQ.
 */
package com.tu.duduse.infrastructure.jooq.tables.records;


import com.tu.duduse.infrastructure.jooq.tables.SpiderQueue;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 爬虫队列
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpiderQueueRecord extends UpdatableRecordImpl<SpiderQueueRecord> implements Record5<String, String, String, Timestamp, Integer> {

    private static final long serialVersionUID = -2046356746;

    /**
     * Setter for <code>spider_queue.ID</code>. 队列id
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>spider_queue.ID</code>. 队列id
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>spider_queue.SPIDER_ID</code>. 爬虫id
     */
    public void setSpiderId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>spider_queue.SPIDER_ID</code>. 爬虫id
     */
    public String getSpiderId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>spider_queue.REQUEST</code>. 请求信息
     */
    public void setRequest(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>spider_queue.REQUEST</code>. 请求信息
     */
    public String getRequest() {
        return (String) get(2);
    }

    /**
     * Setter for <code>spider_queue.CREATETIME</code>. 创建时间
     */
    public void setCreatetime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>spider_queue.CREATETIME</code>. 创建时间
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>spider_queue.QUEUE_INDEX</code>. 序号
     */
    public void setQueueIndex(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>spider_queue.QUEUE_INDEX</code>. 序号
     */
    public Integer getQueueIndex() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Timestamp, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Timestamp, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SpiderQueue.SPIDER_QUEUE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SpiderQueue.SPIDER_QUEUE.SPIDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SpiderQueue.SPIDER_QUEUE.REQUEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return SpiderQueue.SPIDER_QUEUE.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return SpiderQueue.SPIDER_QUEUE.QUEUE_INDEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSpiderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getRequest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getQueueIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSpiderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRequest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getQueueIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpiderQueueRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpiderQueueRecord value2(String value) {
        setSpiderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpiderQueueRecord value3(String value) {
        setRequest(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpiderQueueRecord value4(Timestamp value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpiderQueueRecord value5(Integer value) {
        setQueueIndex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpiderQueueRecord values(String value1, String value2, String value3, Timestamp value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpiderQueueRecord
     */
    public SpiderQueueRecord() {
        super(SpiderQueue.SPIDER_QUEUE);
    }

    /**
     * Create a detached, initialised SpiderQueueRecord
     */
    public SpiderQueueRecord(String id, String spiderId, String request, Timestamp createtime, Integer queueIndex) {
        super(SpiderQueue.SPIDER_QUEUE);

        set(0, id);
        set(1, spiderId);
        set(2, request);
        set(3, createtime);
        set(4, queueIndex);
    }
}
