/*
 * This file is generated by jOOQ.
 */
package com.tu.duduse.infrastructure.jooq.tables.records;


import com.tu.duduse.infrastructure.jooq.tables.SpiderUnique;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpiderUniqueRecord extends UpdatableRecordImpl<SpiderUniqueRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -1892443027;

    /**
     * Setter for <code>spider_unique.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>spider_unique.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>spider_unique.spider_id</code>.
     */
    public void setSpiderId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>spider_unique.spider_id</code>.
     */
    public String getSpiderId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SpiderUnique.SPIDER_UNIQUE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SpiderUnique.SPIDER_UNIQUE.SPIDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSpiderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSpiderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpiderUniqueRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpiderUniqueRecord value2(String value) {
        setSpiderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpiderUniqueRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpiderUniqueRecord
     */
    public SpiderUniqueRecord() {
        super(SpiderUnique.SPIDER_UNIQUE);
    }

    /**
     * Create a detached, initialised SpiderUniqueRecord
     */
    public SpiderUniqueRecord(String id, String spiderId) {
        super(SpiderUnique.SPIDER_UNIQUE);

        set(0, id);
        set(1, spiderId);
    }
}
