/*
 * This file is generated by jOOQ.
 */
package com.tu.duduse.infrastructure.jooq;


import com.tu.duduse.infrastructure.jooq.tables.CoinList;
import com.tu.duduse.infrastructure.jooq.tables.Hosts;
import com.tu.duduse.infrastructure.jooq.tables.IpList;
import com.tu.duduse.infrastructure.jooq.tables.SourceType;
import com.tu.duduse.infrastructure.jooq.tables.Sources;
import com.tu.duduse.infrastructure.jooq.tables.SpiderBase;
import com.tu.duduse.infrastructure.jooq.tables.SpiderQueue;
import com.tu.duduse.infrastructure.jooq.tables.SpiderUnique;
import com.tu.duduse.infrastructure.jooq.tables.SpiderUrl;
import com.tu.duduse.infrastructure.jooq.tables.Tools;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>coin_list</code>.
     */
    public static final CoinList COIN_LIST = com.tu.duduse.infrastructure.jooq.tables.CoinList.COIN_LIST;

    /**
     * The table <code>hosts</code>.
     */
    public static final Hosts HOSTS = com.tu.duduse.infrastructure.jooq.tables.Hosts.HOSTS;

    /**
     * The table <code>ip_list</code>.
     */
    public static final IpList IP_LIST = com.tu.duduse.infrastructure.jooq.tables.IpList.IP_LIST;

    /**
     * The table <code>sources</code>.
     */
    public static final Sources SOURCES = com.tu.duduse.infrastructure.jooq.tables.Sources.SOURCES;

    /**
     * The table <code>source_type</code>.
     */
    public static final SourceType SOURCE_TYPE = com.tu.duduse.infrastructure.jooq.tables.SourceType.SOURCE_TYPE;

    /**
     * 爬虫基本信息
     */
    public static final SpiderBase SPIDER_BASE = com.tu.duduse.infrastructure.jooq.tables.SpiderBase.SPIDER_BASE;

    /**
     * 爬虫队列
     */
    public static final SpiderQueue SPIDER_QUEUE = com.tu.duduse.infrastructure.jooq.tables.SpiderQueue.SPIDER_QUEUE;

    /**
     * The table <code>spider_unique</code>.
     */
    public static final SpiderUnique SPIDER_UNIQUE = com.tu.duduse.infrastructure.jooq.tables.SpiderUnique.SPIDER_UNIQUE;

    /**
     * The table <code>spider_url</code>.
     */
    public static final SpiderUrl SPIDER_URL = com.tu.duduse.infrastructure.jooq.tables.SpiderUrl.SPIDER_URL;

    /**
     * The table <code>tools</code>.
     */
    public static final Tools TOOLS = com.tu.duduse.infrastructure.jooq.tables.Tools.TOOLS;
}
